# Generated by Django 5.2.6 on 2025-09-07 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_familyrelationship'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='familyrelationship',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='familyrelationship',
            name='middle_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='middle_relationships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='familyrelationship',
            name='relation_label',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='familyrelationship',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='familyrelationship',
            name='relationship_type',
            field=models.CharField(max_length=30),
        ),
        migrations.AddIndex(
            model_name='familyrelationship',
            index=models.Index(fields=['from_user', 'to_user', 'relationship_type', 'status'], name='accounts_fa_from_us_2868f8_idx'),
        ),
    ]
